services:
  client: # client用のコンテナ
    build:
      context: client
      dockerfile: Dockerfile
    container_name: client
    tty: true
    volumes:
      - .:/workspace
    working_dir: /workspace/client
    ports:
      - 3000:3000
    networks:
      - bridge
    command: sh -c "pnpm i && pnpm dev"

  server: # server用のコンテナ
    build:
      context: server
      dockerfile: Dockerfile
    container_name: server
    tty: true
    volumes:
      - .:/workspace
    working_dir: /workspace/server
    expose:
      - 3000
    networks:
      - bridge
    command: sh -c "deno task start"

networks:
  bridge:
    driver: bridge
